# Generated by Django 2.2.5 on 2020-01-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registering_app', '0002_auto_20200117_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='verifyPassword',
        ),
    ]
