# Generated by Django 2.2.5 on 2020-01-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registering_app', '0003_remove_members_verifypassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='agreement',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
