# Generated by Django 2.2.5 on 2020-01-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registering_app', '0004_members_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='agreement',
        ),
    ]
