# Generated by Django 2.2.5 on 2020-01-20 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registering_app', '0006_userprofileinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
