# Generated by Django 2.2.5 on 2020-01-16 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessRescord',
            new_name='AccessRecord',
        ),
    ]
